version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
